[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@uniswap/v3-periphery=lib/v3-periphery",
    "@uniswap/v3-core=lib/v3-core",
]
